Add PKGBUILD for installing on arch linux.
TNG/please-cli pull request #36
Opened 2023-06-26 08:37 UTC by NicholasTNG

Add a PKGBUILD for installing on arch linux. I also tried to add creating the package to the github workflow, but I haven't worked with that before and am not confident that it works as intended (I am unsure where the artifact will appear).

2023-06-26 09:39 UTC, thomas-endres-tng requested changes
We should not hardcode the version

2023-06-26 09:39 UTC, thomas-endres-tng commented on PKGBUILD
> +pkgver=0.3.0
Is this hardcoded? It should not be / we should replace that with the current version

2023-06-26 09:39 UTC, thomas-endres-tng commented on PKGBUILD
> +sha256sums=('647242b408b516071e2885531acc0a9b197e37d2523b947d4dad03ba8c690b9e')
Same here

2023-06-26 09:39 UTC, thomas-endres-tng commented on README.md
> +git clone https://github.com/TNG/please-cli.git
Is there no easier way to do this?

2023-06-27 06:41 UTC, NicholasTNG commented on README.md
> +git clone https://github.com/TNG/please-cli.git
If the generated package file (e.g. the output from makepkg from the pipeline) is under the url `https://foo.bar`, this can be simplified to `sudo pacman -U 'https://foo.bar'`. I just don't know enough about the github pipelines to say where that would be.

2023-06-27 07:03 UTC, NicholasTNG commented on PKGBUILD
> +pkgver=0.3.0
It's possible to provide a `pkgver()` function in this file that is run after the source is downloaded and can set the version. It seems easy to get this working in the pipeline, I'll be on it later.

2023-07-19 14:44 UTC, NicholasTNG commented
Please excuse the long wait. I reworked it now in a way that pushes the package automatically to the AUR in the pipeline. This should address all your concerns. The secret key for the aur-account needs to be added to the github secrets for the pipeline. Should I send it to you via encrypted mail or do you prefer another way?

2023-07-19 19:32 UTC, thomas-endres-tng approved these changes

2023-07-19 19:33 UTC, merged