#37: Add current OS
TNG/please-cli pull request #44
Opened 2024-04-26 12:47 UTC by xenia-lang

2025-01-04 12:26 UTC, heiderich commented on please.sh
> +  role="You translate the given input into a bash command for $os. You may not use natural language, but only a bash command as an answer.
I would suggest not to use `bash` as we do not know whether the user is actually using bash or another shell (such as zsh, fish, ...). I would suggest to either use the more generic `shell` (maybe even request the command to be POSIX compliant).

2025-01-05 09:06 UTC, heiderich commented on please.sh
> +  role="You translate the given input into a bash command for $os. You may not use natural language, but only a bash command as an answer.
Alternatively one may retrieve information about the shell in use, e.g. from the `SHELL` env variable.

2025-06-07 20:44 UTC, JonathanRohland-TNG requested changes
Let's make sure that we address the open comments before merging.

2025-06-07 20:44 UTC, JonathanRohland-TNG commented on please.sh
> +  role="You translate the given input into a bash command for $os. You may not use natural language, but only a bash command as an answer.
@heiderich @xenia-lang I'd like to get this PR merged—the idea seems useful to me.
What do you think about getting the current shell name as well as the OS to cover all cases?

e.g. using
```
get_shell()
  if [ -n "$SHELL" ]; then
    current_shell="$(basename "$SHELL")"
  else
    current_shell=""
```

and the adapting the prompt to:
```
  role="You translate the given input into a shell command for $os. The user is running $current_shell. You may not use natural language, but only the command as an answer."
```

2025-06-07 20:44 UTC, JonathanRohland-TNG commented on please.sh
> +  os=get_os
Does the assignment to os in `os=get_os` have any effect at all?
If I read the definition of `get_os` correctly, then it doesn't actually return any value, but directly assign the OS name to the `os` variable.

To return something, shouldn't it be:
```bash
get_os() {
  unameOut=$(uname -s)
  case "$unameOut" in
    Darwin)
      echo "MacOS"
      ;;
    Linux)
      echo "Linux"
      ;;
    *)
      echo "Linux"
      ;;
  esac
}
```

2025-06-07 20:44 UTC, JonathanRohland-TNG commented on please.sh
> +  os=get_os
And then the function call would be `os=$(get_os)`

2025-06-08 15:23 UTC, JonathanRohland-TNG commented
bugbot run

2026-04-15 07:06 UTC, JonathanRohland-TNG commented
Closing this in favor of https://github.com/TNG/please-cli/pull/66

2026-04-15 07:06 UTC, closed without merging